services:
  nordvpn-api:
    build:
      context: .
      dockerfile: Dockerfile.extended
    container_name: nordvpn-api
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NET_LOCAL=192.168.1.0/24
      - VPN_API_PORT=8080
    ports:
      - "8080:8080"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 6
      start_period: 60s
    restart: unless-stopped

  # Example service using the VPN connection (all traffic goes through nordvpn-api via shared network namespace)
  test-service:
    image: alpine:latest
    network_mode: service:nordvpn-api
    depends_on:
      nordvpn-api:
        condition: service_healthy
    command: >
      sh -lc '
        apk add --no-cache curl jq >/dev/null 2>&1 || true;
        echo "VPN API health:"; curl -s http://localhost:8080/health;
        echo; echo "Public IP and geo BEFORE:"; curl -s https://ifconfig.co/json | jq -r ".ip, .country, .country_iso" 2>/dev/null || curl -s https://ifconfig.co/json;
        echo; echo "Requesting switch to UK via VPN API..."; curl -s -X POST http://localhost:8080/switch -H "Content-Type: application/json" -d "{\"country\":\"uk\"}";
        echo; echo "Waiting 25s for reconnection..."; sleep 25;
        echo "Public IP and geo AFTER:"; curl -s https://ifconfig.co/json | jq -r ".ip, .country, .country_iso" 2>/dev/null || curl -s https://ifconfig.co/json;
        echo; echo "API status after switch:"; curl -s http://localhost:8080/status;
        echo; echo "Done."; sleep 300
      '
    restart: unless-stopped